### ISSUE TITLE
Plugin doesn't return anything

### ISSUE THREAD

**Issue by distal-shores** [pasdo501/gatsby-source-woocommerce#11]
Hi,

Thanks for this plugin. I can't seem to get it to return anything, however:

```
    {       
      resolve: '@pasdo501/gatsby-source-woocommerce',
      options: {
         // Base URL of Wordpress site
        api: '<my_endpoint>',
        // true if using https. false if nah.
        https: true,
        api_keys: {
          consumer_key: '<my_key>',
          consumer_secret: <my_secret>',
        },
        // Array of strings with fields you'd like to create nodes for...
        fields: ['products', 'products/categories'],
        // Version of the woocommerce API to use
        // OPTIONAL: defaults to 'wc/v1'
        api_version: 'wc/v3',
        // OPTIONAL: How many results to retrieve
        per_page: 100
      }
    },
```

I just get: `warn The @pasdo501/gatsby-source-woocommerce plugin has generated no Gatsby nodes. Do you need it?` in my output. I've verified I can access the WooCommerce API via url params manually in the browser so I'm sure it exists and is open.

I'm also using the `gatsby-source-wordpress` plugin, which can see the woocommerce data endpoints but 401s on them.

**Comment by pasdo501** [comment]
Hi there,

Hmm I'm not sure what's going on there. I tested with a clean gatsby project (using just wordpress source & this) and it pulled in products fine. I don't see anything wrong in your config, either (it would display a block, before the warning you're seeing, along the lines of `========== WARNING FOR FIELD products/categories ==========` followed by the json response if the api / api keys were wrong).

Probably a silly question, but to cover all bases: have you created any products or product categories on the Wordpress site yet? It would behave the way it has for you (No warnings other than the hasn't generated Gatsby nodes message) if that was the case.

Another thing you could try is to use the [WooCommerce API node package](https://www.npmjs.com/package/woocommerce-api) to see if that also returns nothing. If you get nothing back from that either, it might be some configuration thing on the Wordpress site, but if you do get data, it'll definitely be something wrong with this plugin.

Keep me posted, we'll get it sorted out!

**Comment by distal-shores** [comment]
Tried to test via the node-woocommerce API but got hung up at build (`gatsby develop`) with this error

```
This dependency was not found:
⠀
* fs in ./node_modules/request/lib/har.js
```

Which, no matter what I did with yarn/npm would not resolve. So yeah maybe something is off with my environment, I will try the same creds on a fresh gatsby install and let you know how if it works.

**Comment by distal-shores** [comment]
Oh man I feel like a real dummy, I didn't even try to run it with `https:` set to `false`. I guess my S3 installation of wordpress on a subdomain of my encrypted DNS is not as secure as I thought it was! 

Sorry for the non-issue, closing.

**Comment by pasdo501** [comment]
Oh, oops! No worries at all, and glad to hear you found the cause.

**Comment by jarangit** [comment]
========== WARNING FOR FIELD products ===========
            The following error status was produced: Error: Request failed with status code 400
            ================== END WARNING ==================

I encountered this problem, how do I solve it?
![image](https://user-images.githubusercontent.com/52028847/72199450-dd2d4580-346e-11ea-90cf-45ffcca548f4.png)
![image](https://user-images.githubusercontent.com/52028847/72199457-f0d8ac00-346e-11ea-8e54-6da54c76db1e.png)

Help me please
