### ISSUE TITLE
SyntaxError: Unexpected reserved word

### ISSUE THREAD

**Issue by zamson** [pasdo501/gatsby-source-woocommerce#13]
Hi,
first of all thanks for taking the time to maintain this project. I'm currently exploring using Gatsby for WooCommerce.

I get an error when running `gatsby develop`:

```
Error: */node_modules/@pasdo501/gatsby-source-woocommerce/helpers/index.js:44
    for await (let node of nodes) {
        ^^^^^
  SyntaxError: Unexpected reserved word
```

Any ideas? Maybe related to [this](https://stackoverflow.com/questions/42299594/await-is-a-reserved-word-error-inside-async-function).

**Comment by zamson** [comment]
You can close this issue. Turns out I needed to upgrade Node to v12.

**Comment by pasdo501** [comment]
Hi,

Glad to hear you were able to resolve the issue! Will close this now.
