### ISSUE TITLE
Creating node from woocommerce for more then 500 products result in ECONNRESET and Error: socket hang up and

### ISSUE THREAD

**Issue by gvocale** [pasdo501/gatsby-source-woocommerce#28]
I have a woocommerce site with 12000 products running on localhost via MAMP. I am trying to move these products to gatsby, so in gatsby-node.js I am creating 12000 pages and downloading the images for each product.

If I limit to less then 500 producs, all works well. More then that, as I try to download the images and write them to a local folder via Axios I run into ECONNRESET.

By using `agentkeepalive` things improved a bit, but now I am getting `Error: socket hang up` after I pass 400~ images downoaded. I guess my mysql server is timing out and closing the connection to node, which, by trying to create page from 12000 products and download all images, takes longer then the mysql timeout.

Have you ever run into a similar issue? Do you have any suggestion of what I could try? This is an example of the code I'm working with:

```js
const Path = require(`path`)
const filePath = Path.resolve(process.cwd())

const Agent = require("agentkeepalive")

const keepAliveAgent = new Agent({
  maxSockets: 100,
  maxFreeSockets: 10,
  timeout: 60000, // active socket keepalive for 60 seconds
  freeSocketTimeout: 30000, // free socket keepalive for 30 seconds
})

const AxiosInstance = Axios.create({ httpAgent: keepAliveAgent })

exports.createPages = async function createPages({ graphql }) {
  const result = await graphql(
    `
      query Produts {
        allWcProducts(limit: 1000) {
          edges {
            node {
              price
              sale_price
              name
              categories {
                name
                slug
              }
              description
              images {
                src
              }
              slug
            }
          }
          totalCount
        }
      }
    `
  )

  if (result.errors) throw new Error(result.errors)

  result.data.allWcProducts.edges.forEach(async (edge, productIndex) => {
    const { images, slug } = edge.node
    const data = JSON.stringify(edge.node, null, 2)
    const capital = slug.slice(0, 1).toUpperCase()
    const folder = `${filePath}/content/${capital}/${slug}`

    try {
      await Fs.mkdirSync(folder, { recursive: true })
      await Fs.writeFileSync(`${folder}/index.json`, data)
      // try to save images
      const uniqueImages = images.reduce((accumulator, currentValue) => {
        if (!accumulator.includes(currentValue.src))
          accumulator.push(currentValue.src)
        return accumulator
      }, [])
      for (const url of uniqueImages) {
        const fileName = `${folder}/${url.split("/").pop()}`
        const writer = Fs.createWriteStream(fileName)
        const response = await AxiosInstance({
          url,
          method: "GET",
          responseType: "stream",
          headers: {
            Connection: "keep-alive",
            "User-Agent":
              "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36",
          },
        })
        response.data.pipe(writer)
      }
    } catch (error) {
      Logger.log(error)
    }
  })
}
```

**Comment by pasdo501** [comment]
Hi there,

I've unfortunately never run into a similar issue, I'm afraid! Does the build work using the 12000 products, if you exclude the image download step in the second half of that code?

If it does, could you skip downloading the images again and just move the ones gatsby downloaded to speed things up? Using something like 

```
`
      query Produts {
        allWcProducts(limit: 1000) {
          edges {
            node {
              price
              sale_price
              name
              categories {
                name
                slug
              }
              description
              images {
                localFile {
                    absolutePath
                }
              }
              slug
            }
          }
          totalCount
        }
      }
    `
```

It's a little late here and I may be misunderstanding what you're trying to do with the images, though, so apologies if that's the case or this made little sense! Hopefully we can get there!

**Comment by gvocale** [comment]
Without downloading the images the build runs successfully for all 12000 products.

I have changed keep alive settings to the following and I manage to download 90% of the images successfully out of 45000 images. The remaining 10% comes out of 0 byte size, even if the original url contains a correct working image.
 
```
const keepAliveAgent = new Agent({
  maxSockets: 100,
  maxFreeSockets: 10,
  timeout: 9999999,
  freeSocketTimeout: 9999999,
})
```

I will try again using `absolutePath`, but I'm afraid the issue is mysql timing out connections to node after a certain time or node trying to download too many at the same time.

**Comment by pasdo501** [comment]
Cool - the reason I asked is that the plugin already downloads all product images as part of the build process, so unless I'm still confused about what you're doing with the images, it's really double handling the downloads.

If you don't want the plugin to download the images, and want to handle that yourself, maybe commenting out lines 121 - 128 in the plugin's `gatsby-node.js` file would speed up the process and avoid the timeout?

**Comment by gvocale** [comment]
@pasdo501 using absolutePath and node `copyFile` worked! I get no errors anymore. I just didn't know better so I was trying to "download" them with axios even if the files were already on the hard drive

**Comment by pasdo501** [comment]
Glad to hear it worked!
