### ISSUE TITLE
Error 508 while fetching product variations

### ISSUE THREAD

**Issue by andelh** [pasdo501/gatsby-source-woocommerce#29]
For some reason, some of my product variations/attributes are being pulled in and some are not. I initially thought it was because I did not set a default variation in WooCommerce but that doesn't seem to be the case. Can anyone help with this?

warn
              Warning: error while fetching variations for Ridley Grey 4pc Printed Sheet Set
 (85GSM).
              Error: Error: Request failed with status code 508.
warn
              Warning: error while fetching variations for Intex Prism Frame Above Ground
Swimming Pool Set with Filter.
              Error: Error: Request failed with status code 508.
warn
              Warning: error while fetching variations for Jaxton 4pc Printed Sheet Set
(85GSM).
              Error: Error: Request failed with status code 508.

**Comment by andelh** [comment]
Hey thanks for responding! 

- Yep it's the same products every time, it just reverses the order the products with error messages show in every time i run 'gatsby develop'

- Posting screenshots of the variations setup below. The fields filled for the Variations are price and description.

<img width="950" alt="Screen Shot 2020-04-10 at 11 30 45 AM" src="https://user-images.githubusercontent.com/9642862/79002655-e934ac00-7b1e-11ea-9953-8a417fd8d8b8.png">
<img width="946" alt="Screen Shot 2020-04-10 at 11 31 30 AM" src="https://user-images.githubusercontent.com/9642862/79002662-ed60c980-7b1e-11ea-95e9-a9dc05039d0d.png">

**Comment by pasdo501** [comment]
Thanks for that - I'll take a look when I get a chance. Based on the error it looks like something I do when pulling in the variations causes a loop, will get back to you!

**Comment by pasdo501** [comment]
Hi again,

Sorry for the delay!

I haven't been able to reproduce a similar error. Would you be able to make a request using the [WooCommerce API package](https://www.npmjs.com/package/@woocommerce/woocommerce-rest-api) in a blank project (just to see if the endpoint itself always returns that error). The endpoint you want is `products/<product_id>/variations` - based on the code execution it's actually that part that's failing (although it wouldn't help too much with finding out why, if that fails, can deal with that if it comes to it).
