### ISSUE TITLE
GraphQLError: Schema is not configured for mutations. when doing Mutation

### ISSUE THREAD

**Issue by kenchoong** [pasdo501/gatsby-source-woocommerce#31]
I wanna to know the this plugin only can pull data is it or  is it possible to run Mutation? 

For example I want to run the following Query: 

I found this code about from here https://woographql.com/introduction which is WPGraphQL WooCommerce plugin docs. 

```
mutation {
  addToCart(input: {clientMutationId: "someId" productId: 22, quantity: 2}) {
    clientMutationId
    cartItem {
      key
      product {
        id
        productId
        name
      }
      quantity
      subtotal
      total
    }
    cart {
      contents(first: 10) {
        edges {
          cursor
          node {
            key
            quantity
            subtotal
            total
          }
        }
      }
      subtotal
      total
    }
  }
}
```

But I get the following error 
`
GraphQLError: Schema is not configured for mutations.
`

Here is my package.json file 

```
{
      resolve: "@pasdo501/gatsby-source-woocommerce",
      options: {
        // Base URL of WordPress site
        api: `mysite.com`,
        // true if using https. false otherwise.
        https: false,
        api_keys: {
          consumer_key: "key",
          consumer_secret: "sercet",
        },
        // Array of strings with fields you'd like to create nodes for...
        fields: ['products', 'products/categories', 'products/attributes',
            'orders', 'customers','coupons'
      
        ],
      }
    },
```

I dont understand why I can run the mutation? Is it something I miss out??

**Comment by pasdo501** [comment]
Hello! This plugin isn't currently set up for mutations, sorry - it can only pull data.

**Comment by kenchoong** [comment]
@pasdo501 ok thanks..

**Comment by pasdo501** [comment]
I'm pretty busy at the moment, but if I get a chance I'll look into what's required to allow mutations. I'll ping you if I do (just in case you're still interested at that point).

Also, I recommend keeping an eye on https://github.com/wp-graphql/wp-graphql-woocommerce which will be a much more comprehensive plugin when it's done, with a much bigger team maintaining it.
