### ISSUE TITLE
Error: connect ECONNREFUSED 127.0.0.1:8080 

### ISSUE THREAD

**Issue by SravanKumar35** [pasdo501/gatsby-source-woocommerce#32]
I am using wordpress website Local by flywheel ( url: xyz.local ) . I created a new gatsby site using and added gatsby-source-woocommerce. I also generated consumer key and consumer secret from woo-commerce settings. i added them to the api_keys in the config file. 

When i run gastby develop, i get this error. 

   ========== WARNING FOR FIELD products ===========
            The following error status was produced: Error: connect ECONNREFUSED 127.0.0.1:8080
            ================== END WARNING ==================

08:19:23.204Z > gatsby-source-woocommerce: Fetching 0 nodes for field: products
08:19:23.206Z > gatsby-source-woocommerce: Completed fetching nodes for field: products
warn
            ========== WARNING FOR FIELD products/categories ===========
            The following error status was produced: Error: connect ECONNREFUSED 127.0.0.1:8080
            ================== END WARNING ==================

08:19:23.213Z > gatsby-source-woocommerce: Fetching 0 nodes for field: products/categories
08:19:23.215Z > gatsby-source-woocommerce: Completed fetching nodes for field: products/categories
warn
            ========== WARNING FOR FIELD products/attributes ===========
            The following error status was produced: Error: connect ECONNREFUSED 127.0.0.1:8080
            ================== END WARNING ==================

Can someone pls say if did i miss anything? or any wrong i have done?

**Comment by pasdo501** [comment]
Hello!

I'd have a look into what you're pointing the plugin at (the api setting in the config) to make sure the url / port is correct. I would guess it's related to the set up of your local site.

**Comment by SravanKumar35** [comment]
Hii, 
So local by flywheel allows us to run our wordpress site locally on our computer. 
Please look into this plugin:

`
{
      resolve: "@pasdo501/gatsby-source-woocommerce",
      options: {
        // Base URL of Wordpress site
        api: "xyz.local",

        // set to false to not see verbose output during build
        // default: true
        verbose: true,

        // true if using https. otherwise false.
        https: false,
        api_keys: {
          consumer_key: `ck_*****************************************************`,
          consumer_secret: `cs_*******************************************************`,
        },
        // Array of strings with fields you'd like to create nodes for...
        fields: ["products", "products/categories", "products/attributes"],
        // Send the API keys as query string parameters instead of using the authorization header
        // OPTIONAL: defaults to false
        query_string_auth: false,
        // Version of the woocommerce API to use
        // OPTIONAL: defaults to 'wc/v3'
        api_version: "wc/v3",
        // OPTIONAL: How many results to retrieve *per request*
        per_page: 100,
        // OPTIONAL: Custom WP REST API url prefix, only needed if not using
        // the default wp-json prefix.
        wpAPIPrefix: "wp-rest",
        // OPTIONAL: Support for URLs with ports, e.g. 8080; defaults to no port
        port: "8080",
        // OPTIONAL: Encoding; default to 'utf8'
        encoding: "utf8",
        // OPTIONAL: Custom Axios config (see https://github.com/axios/axios) - note that this can override other options.
        axios_config: {
          // Axios config options
        },
      },
    },
`

**Comment by SravanKumar35** [comment]
Hi, I solved the problem. In case if someone else got struck in same problem. 

here is the solution. 
In config options of gatsby-source-woocommerce, 
comment everything after fields i.e After commenting it looks like, 



`

{


      resolve: "@pasdo501/gatsby-source-woocommerce",

      options: {

        // Base URL of Wordpress site

        api: "wordpress.domain",

        // set to false to not see verbose output during build
        // default: true
        verbose: true,

        // true if using https. otherwise false.
        https: false,
        api_keys: {
          consumer_key: <key>,
          consumer_secret: <secret>,
        },
        // Array of strings with fields you'd like to create nodes for...
        fields: ["products", "products/categories", "products/attributes"],

       
      },
    },`

Head to the @pasdo501/gatsby-source-woocommerce folder ( node modules ) -> gatsby-node.js 

change api_version = "wc/v3" to "wc/v2" and 
change wpAPIPrefix = null to "wp-json" 
and save it.

voila


I'm closing this issue now, In case if someone has same problem and if above solution is not working, feel free to reopen the issue
