### ISSUE TITLE
error while running the createSchemaCustomization lifecycle

### ISSUE THREAD

**Issue by andreyc0d3r** [pasdo501/gatsby-source-woocommerce#34]
HI,

Thank you for the repo, it is very helpful.

However I came accross this error, not sure why, hopefully you could help:

![image](https://user-images.githubusercontent.com/5830381/108352648-428b6280-723b-11eb-8681-80a3e7bf8d8d.png)

**Comment by pasdo501** [comment]
Hi there,

Could you check if in your `gatsby-config.js` file, the `fields` property is properly set? Based on the error message there might be an issue with it?

**Comment by andreyc0d3r** [comment]
> Hi there,
> 
> Could you check if in your `gatsby-config.js` file, the `fields` property is properly set? Based on the error message there might be an issue with it?

Thank you for your proptreply. Fields are not set. I was following the documentation.  I dont recall seeing fields. If i do need to set them can you please point me to the right doc for instructions.  Thanks

**Comment by pasdo501** [comment]
Just to be clear, I mean `fields` property on the options for this particular plugin, not at the top level of `gatsby-config.js`. It's in the example config snippet of the readme, in the How to Use section, and the section immediately following it (relevant part of the config below) - 

```
...
// Array of strings with fields you'd like to create nodes for...
fields: ['products', 'products/categories', 'products/attributes'],
...
```

**Comment by andreyc0d3r** [comment]
thank you problem resolved
