### ISSUE TITLE
Error: getaddrinfo ENOTFOUND https

### ISSUE THREAD

**Issue by instantwpuserwin** [pasdo501/gatsby-source-woocommerce#35]
Hi there

I am getting  following error. 
Please help. Thank you.

            ========== WARNING FOR FIELD products ===========
            The following error status was produced: Error: getaddrinfo ENOTFOUND https
            ================== END WARNING ==================

==============
console outout:
uccess open and validate gatsby-configs - 0.218s
success load plugins - 30.317s
success onPreInit - 0.111s
success initialize cache - 0.008s
success copy gatsby files - 2.965s
success onPreBootstrap - 0.224s
success  gatsby-source-wordpress  ensuring plugin requirements are met - 0.020s
success  gatsby-source-wordpress  diff schemas - 7.675s
success  gatsby-source-wordpress  ingest WPGraphQL schema - 7.986s
success createSchemaCustomization - 8.101s
success  gatsby-source-wordpress  fetch root fields - 4.130s
success  gatsby-source-wordpress  pull updates since last build - 4.162s
warn
            ========== WARNING FOR FIELD products ===========
            The following error status was produced: Error: getaddrinfo ENOTFOUND https
            ================== END WARNING ==================

06:40:59.854Z > gatsby-source-woocommerce: Fetching 0 nodes for field: products
06:40:59.856Z > gatsby-source-woocommerce: Completed fetching nodes for field: products
warn
            ========== WARNING FOR FIELD products/categories ===========
            The following error status was produced: Error: getaddrinfo ENOTFOUND https
            ================== END WARNING ==================

06:40:59.863Z > gatsby-source-woocommerce: Fetching 0 nodes for field: products/categories
06:40:59.865Z > gatsby-source-woocommerce: Completed fetching nodes for field: products/categories
warn
            ========== WARNING FOR FIELD products/attributes ===========
            The following error status was produced: Error: getaddrinfo ENOTFOUND https
            ================== END WARNING ==================

06:40:59.871Z > gatsby-source-woocommerce: Fetching 0 nodes for field: products/attributes
06:40:59.874Z > gatsby-source-woocommerce: Completed fetching nodes for field: products/attributes
06:40:59.875Z > gatsby-source-woocommerce: Fetching product variations for 0 nodes
06:40:59.877Z > gatsby-source-woocommerce: 0 product variations retrieved for 0 nodes in 0s
06:40:59.878Z > gatsby-source-woocommerce: Fetching product attributes for 0 nodes
06:40:59.880Z > gatsby-source-woocommerce: 0 product attributes terms retrieved for 0 nodes in 0s
06:40:59.882Z > gatsby-source-woocommerce: 0 nodes mapped, processed, and created in 0s
warn The @pasdo501/gatsby-source-woocommerce plugin has generated no Gatsby nodes. Do you need it?
success Checking for changed pages - 0.002s
success source and transform nodes - 4.323s
success building schema - 1.487s
info Total nodes: 55, SitePage nodes: 3 (use --verbose for breakdown)
success createPages - 0.142s
success Checking for changed pages - 0.001s
success createPagesStatefully - 0.086s
success update schema - 0.222s
success write out redirect data - 0.002s
success Build manifest and related icons - 0.255s
success onPostBootstrap - 0.262s
info bootstrap finished - 114.728s
success onPreExtractQueries - 0.002s
success extract queries from components - 1.837s
success write out requires - 0.015s
success run page queries - 0.033s - 1/1 30.02/s
not finished Building development bundle - 9.319s
===============

Part of gatsby-config.js  below:

plugins: [
    {
      resolve: `gatsby-source-wordpress`,
      options: {
        url:
          process.env.WPGRAPHQL_URL ||
          `https://top10hostingonweb.com/woodemo/graphql`,
      },
    },

    {
      resolve: "@pasdo501/gatsby-source-woocommerce",
      options: {
        // Base URL of WordPress site
        api: 'https://top10hostingonweb.com/woodemo/',
        // true if using https. false otherwise.
        https: true,
        api_keys: {
          consumer_key: `ck_e75bfe2c9b8ef1c6886f92134cf720505cad2837`,
          consumer_secret: `cs_3e6e3ff56cdf2889192dcf8122752f039721d9b1`,
        },
        // Array of strings with fields you'd like to create nodes for...
        fields: ['products', 'products/categories', 'products/attributes'],
      }
    },

**Comment by pasdo501** [comment]
Hi there,

My guess it's including the protocol into the url given for the `api` option. Could you try without the `https://` for that value and let me know if that works? Seems like something that's worth changing to accept it either way especially since it's not made clear that it could lead to issues.

Cheers

**Comment by instantwpuserwin** [comment]
Yes.  That worked. 

Thanks a lot.  Cheers
