### ISSUE TITLE
Using gatsby-woocommerce plugin for fetching data dynamically

### ISSUE THREAD

**Issue by petervidaHU** [pasdo501/gatsby-source-woocommerce#37]
Hi, probably this is a lame question, but I am a junior. 
So, I want to use this plugin for fetching data dynamically, when a user using the webshop. For example, checking my orders, update the shipping address, and the most important: making an order.
My question, that, am I doing this right? I tried to make some queries about adding new orders, get all orders, without too much success. 
I tried this, for example:

query samplequery {
  allWcOrders {
    edges {
      node {
        id
      }
    }
  }
}

Probably, am I have to use a simple fetch() with JSON and the Rest API, not graphql, and not this plugin?

**Comment by pasdo501** [comment]
Hi there,

No problem! For dynamic things like orders, address etc, you'd be better off to use the WooCommerce REST API as you say. This plugin is just for the build step, so it'd make sense to use it for stuff that won't change much. If you haven't seen yet, [this link](https://www.gatsbyjs.com/docs/conceptual/data-fetching/) could be useful for the general idea?

**Comment by petervidaHU** [comment]
Hi, thank you for your answer.
