### ISSUE TITLE
Can't get "edges" field there

### ISSUE THREAD

**Issue by Miskannn** [pasdo501/gatsby-source-woocommerce#41]
![image](https://user-images.githubusercontent.com/91850607/204823885-47fee73b-c677-4643-b654-835c5606ea3e.png)

**Comment by Miskannn** [comment]
On wordpress we have such types as "BundleProduct and SimpleProduct", here they are also with the prefix Wp, and we can't get  "edges" field in WpBundleProduct definition, but we can get that field in wordpress graphql. @pasdo501 Can you please say what a problem, and how to fix that?

**Comment by pasdo501** [comment]
Hi @Miskannn - if this is under WpBundleProduct, that wouldn't be created by this plugin. This plugin creates all fields with the `wc` prefix, not Wp. Can you confirm whether or not the fields in the screenshot are under the wcProduct node or not?

**Comment by pasdo501** [comment]
Hi @Miskannn - the query you've linked to in that gist is on the `wpProduct` node -- that's unrelated to this plugin. I'm guessing you have `gatsby-source-wordpress` installed? If so, that's the plugin creating those nodes. This plugin only creates nodes like `wcProduct`. Having said that, I'm not entirely sure if it would include the data you're after, either. That would depend on whether or not those plugins add data to the Woocommerce REST API or not. If they do, you may be in luck.
