### ISSUE TITLE
Releated Products

### ISSUE THREAD

**Issue by anamwp** [pasdo501/gatsby-source-woocommerce#7]
Hello, 
How can I show related Products in the single product page. 
Your query only give me ID of related products. 
But I can not manage those related products associated with single product. 
Any help is appreciated. 
Thanks.

**Comment by pasdo501** [comment]
Hello!

I've pushed an update that should enable you to access related products more easily. Before, you would have had to pull in the related IDs, followed by another GraphQL query using those IDs to get the products of interest, but now you should be able to query them under the related_products fields of each product (with the same fields a normal product would have -- see the [4th example in the readme](https://github.com/pasdo501/gatsby-source-woocommerce#some-graphql-query-examples)).

I'll also copy it here just in case, with an example product with an ID of 12:
```graphql
{
  wcProducts(wordpress_id: {eq: 12}) {
    name
    price
    related_products {
      name
      // etc - same fields as a normal product
    }
  }
}
```

Let me know if that helps you at all!

**Comment by anamwp** [comment]
Thanks 
Its works like charm. 
But I have another problem for `grouped product`. 
It also give me those id which associated with group product product. 
Here I attach two image of what I am talking about.
https://monosnap.com/file/To0c8VhZhSOu0i3fqgHgGJ0e26Ywok
https://monosnap.com/file/rcaVVnJRNWZOUfEyAWMtuWUXXYJ4vA
I will try to contribute with you very soon. 
I like this plugin. 
Thanks.

**Comment by pasdo501** [comment]
Thanks for pointing that out! Give it a go with the latest update.

To access the products in the group, try this:

```graphql
{
  wcProducts(wordpress_id: {eq: 35}) {
    # Your other fields - name, price etc
    grouped_products_nodes {
      name
      # Whatever fields you are interested in
    }
  }
}

Let me know if that works / is useful

**Comment by anamwp** [comment]
Yes, its works. 
Appreciate your help.
Thank you very much.

**Comment by pasdo501** [comment]
Fantastic, glad to hear it!

I'll close the issue then, but obviously feel free to re open if anything else crops up.

Thanks for helping me improve the plugin! :smile:
