### ISSUE TITLE
Showing stock of variations

### ISSUE THREAD

**Issue by MartinConde** [pasdo501/gatsby-source-woocommerce#9]
Hi, first of all thanks a lot for taking over the plugin ;)

Not really an issue with the plugin more of a mental blockade I can't seem to get around so was hoping you might have an idea:

Basically I wanna mimic the class WooCommerce behavior where it will show "X in stock" or "Out of stock" depending on the variations selected. I tried stealing the logic from the Woo PHP template but that only got me so far..

```
 {product.attributes.map(attribute => (
          <div>
            {attribute.name}
            {attribute.options.map(option => (
              <label>
                <input
                  type="radio"
                  name={attribute.name}
                  onChange={this.handleChange}
                  value={option}
                />
                {option}
              </label>
            ))}
          </div>
        ))}
```

This will basically give me all the attributes. Any ideas or pointers on how to check the selection against the variations and then show the stock?

**EDIT**
I think I am onto something even though it feels very hacky haha but it seems to work:

In my render function I have:

```
const product = this.props.data.wcProducts

    let allVariations = product.product_variations

    const availability = allVariations.filter(
      p =>
        p.attributes[0].option === this.state.color &&
        p.attributes[1].option === this.state.size
    )

    const stockQuantity = availability.find(x => (x.stock_status = "instock")).stock_quantity
```

and then as I select options I can show the stock using:

```
 <div>
          {stockQuantity > 0 ? "in stock " : "out of stock "}
          {stockQuantity}
</div>
```

Very hacky so if anybody has some ideas on how to properly link it to variations etc that'd be great :)

**Comment by pasdo501** [comment]
Hi there,

I personally haven't used variations in any build I've used the plugin for yet, so I haven't come across that myself yet (but definitely see what you mean). 

Off the top of my head, and without having tried it myself, another option could be to rearrange the data on component mount to make it more easily accessible based on the selected variation. Something like an object with keys made up of the variation attributes? 

For example, if you had size & colour, as you map over the variations, you could create keys like large_blue which would then contain all the variation's data (including the stock), which you should then be able to access using ``obj[`${this.state.size}_${this.state.color}`]``. Something important to keep in mind, though, is that if you have an attribute that can be 'any' in a variation, it'll not show up as an attribute of that variation, so will need to account for those cases. So a variation described by large size and any colour might be accessed (using the method described above) under ``obj['large']`` (with only one attribute making up the key). 

The flow could be: change an attribute selection (e.g size) -> check your variation object's key made up of currently selected size & colour -> if that key exists, use that data, if not, check by just colour and then size at a time (to match the 'any' attribute variations). Seems like this will turn into a bit of a pain in the arse if you have more than two attributes, and may not be any better than what you have already anyway! I hope you can see where I was going with that anyway haha. 

Perhaps someone will come along with a better idea!
